id: P010317
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-19 20:43:45.903320
source_metadata:
  id: bdr:W1KG10631
  title: དབང་ཆེན་པདྨ་རིག་འཛིན་གྱི་གསོ་རིག་རྩོམ་ཡིག་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    0d92094d955848059cb4f403dc53e83a:
      image_group_id: I1KG10636
      title: ''
      volume_number: 1
      total_pages: 240
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
