id: I55943835
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T14:37:18+00:00'
last_modified: '2022-06-08T12:42:11.116626+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG10631
  title: དབང་ཆེན་པདྨ་རིག་འཛིན་གྱི་གསོ་རིག་རྩོམ་ཡིག་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    8DE7:
      image_group_id: I1KG10636
      title: ''
      total_pages: 240
      order: 1
      base_file: 8DE7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
